# Site settings
name: "Stéphane FEUGA OSHIMA"
description: "Software Engineer with a Ruby Addiction.<br/>I'm also a Computer Graphics Enthusiast!"
#last_sentence: ""
url: ""

## 5 elements are recomended
#AngelList: sfeuga
#Blog: https://blog.sfeuga.com
#CodePen: your_codepen_username_goes_here
#DeviantArt: sfeuga
#Facebook: your_facebook_username_goes_here
#Flickr: your_flickr_username_goes_here
#GitHub: sfeuga
#GitLab: sfeuga
#IMDB: ur123023411
#Instagram: your_instagram_username_goes_here
#LastFM: your_lastfm_username_goes_here
#Medium: your_medium_username_goes_here
#Reddit: your_reddit_username_goes_here
#Slack_space: sfeugaoshima
#SoundCloud: your_soundcloud_username_goes_here
#Spotify: famille-feuga--oshima
#Stack: your_stack_overflow_account_id_number_goes_here
#Steam: sfeuga
#Tumblr: your_tumblr_username_goes_here
#Vine: your_vine_username_goes_here
#VK: your_vk_username_goes_here
#Weibo: your_weibo_username_goes_here
Email: sfeuga@member.fsf.org
LinkedIN: sfeuga
Public_Key: https://raw.githubusercontent.com/sfeuga/sfeuga.github.io/master/assets/public.2021-05-10.key
Skype: dFiwqCSpg0Vb
Telegram: sfeuga
Twitter: sfeuga

#avatar: "assets/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar: https://avatars3.githubusercontent.com/u/5821408


bg_img: assets/background.jpg
#bg_img: https://external.url/image.jpg


#favicon: assets/favicon.ico
#favicon: https://external.url/favicon.ico


# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .gitignore
  - .gitlab-ci.yml
  - .jekyll-metadata
  - .ruby-version
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
